language: csharp
solution: MessageMediaMessages.sln
install:
  - nuget restore MessageMediaMessages.sln
  - nuget install NUnit.Runners -Version 3.2.1 -OutputDirectory testrunner
script:
  - msbuild /t:restore /p:Configuration=Release MessageMediaMessages.sln
  - msbuild /p:Configuration=Release MessageMediaMessages.sln
 
